

INSERT INTO Book (title, description, author_name, publication_date, genre, isbn, price, pages, language, publisher) 
VALUES 
('To Kill a Mockingbird', 'To Kill a Mockingbird is a powerful and evocative novel by Harper Lee, set in the deep South during the 1930s. This work of historical fiction examines the themes of racial injustice, moral growth, and empathy, through the eyes of young Scout Finch. The story takes place in the town of Maycomb, Alabama, and is shaped by the trial of Tom Robinson, an African American man falsely accused of raping a white woman, Mayella Ewell. Through Scout’s narration, Lee brings to life a community where racism and prejudice are deeply embedded in everyday life. The story revolves around Scout’s father, Atticus Finch, a wise and moral lawyer who is appointed to defend Robinson. Despite his best efforts, the deeply entrenched racism of the time leads to an unjust conviction. This heartbreaking event forces Scout, her brother Jem, and their father to confront uncomfortable truths about their society. Lee’s portrayal of the Finch family’s moral courage in the face of hate and bigotry has made the book a classic of American literature. Atticus’s steadfast belief in justice, even when it seems impossible, offers a poignant lesson in integrity. Scout’s journey from innocence to understanding reflects the harsh realities of growing up and facing societal injustices. The novel challenges readers to examine their own moral values and the role they play in perpetuating or combating systemic discrimination. To Kill a Mockingbird continues to resonate with readers, inspiring conversations about race, equality, and the human condition. It remains a seminal work in both educational and literary circles, exploring universal themes that are as relevant today as when the book was first published.', 'Harper Lee', '1960-07-11', 'Historical Fiction', '9780061120084', 14.99, 281, 'English', 'J.B. Lippincott & Co.'),
('The Psychology of Money', 'In The Psychology of Money, Morgan Housel presents a unique perspective on personal finance by emphasizing the role of human behavior in shaping financial success. Rather than focusing solely on strategies for accumulating wealth, Housel explores how our emotions, biases, and mental habits affect the financial decisions we make throughout our lives. Housel delves into various stories, both historical and modern, to demonstrate how the psychology behind money influences decisions about saving, investing, and spending. He points out that success in managing money is often more about behavior than knowledge. Traits such as patience, discipline, and a long-term mindset are essential for achieving financial stability, while emotional responses to fear, greed, and short-term gains can lead to financial pitfalls. A recurring theme in the book is the idea that wealth is often invisible. People may appear wealthy based on their possessions or lifestyle, but true wealth often lies in the savings and investments that are not on display. Housel also discusses the relationship between money and happiness, noting that while money can contribute to a better quality of life, it does not guarantee happiness. The key to contentment, according to Housel, lies in aligning one’s financial goals with personal values and maintaining a sense of peace with one’s financial choices. The Psychology of Money is an insightful and accessible guide to understanding how our attitudes toward money shape our financial outcomes. It encourages readers to rethink their approach to money and offers practical advice for building wealth that lasts, not just in terms of finances, but in overall life satisfaction.', 'Morgan Housel', '2020-09-08', 'Finance', '9780857197689', 12.99, 256, 'English', 'Harriman House'),
('Charlotte''s Web', 'Charlotte’s Web, written by E. B. White, is a timeless children’s classic about the unlikely friendship between a pig named Wilbur and a spider named Charlotte. Set on a farm, the story centers on Wilbur, a young pig who is saved from being slaughtered by Charlotte, who writes messages in her web to convince the farmer that Wilbur is special. Through Charlotte’s creative and selfless actions, Wilbur is given a chance at life. As Wilbur grows and faces challenges, Charlotte remains by his side, offering guidance and support. The story explores important themes such as friendship, loyalty, sacrifice, and the cycle of life. Charlotte’s Web has resonated with generations of readers, offering important life lessons through its simple yet profound narrative. It encourages readers to understand the power of kindness, selflessness, and the importance of standing up for others. At its core, Charlotte’s Web is a celebration of the beauty of life, both in its fleeting moments and its enduring impact. The story is beloved for its heartwarming portrayal of the bonds that form between different creatures, transcending differences to show that love and loyalty can come in all shapes and sizes. The timeless nature of Charlotte’s Web makes it an essential book for young readers, and its lessons continue to speak to people of all ages about the importance of compassion and friendship.', 'E. B. White', '1952-10-15', 'Children''s Literature', '9780064400558', 7.99, 192, 'English', 'Harper & Brothers'),
('I Don''t Love You Anymore', 'I Don’t Love You Anymore is a self-help book written by Rithvik Singh that explores the emotional challenges of moving on from a relationship. Drawing on personal experiences, the book provides practical advice on how to cope with heartbreak, rediscover self-worth, and rebuild one’s life after a painful breakup. Singh emphasizes the importance of healing and offers strategies to help individuals move forward emotionally and mentally. The book covers various stages of the healing process, from grieving the end of the relationship to finding strength in solitude and rediscovering passion and purpose in life. Singh encourages readers to embrace change and see it as an opportunity for personal growth. He also stresses the importance of forgiveness, both toward oneself and others, to let go of negative emotions and find peace. I Don’t Love You Anymore is a compassionate and insightful guide that speaks to those who have experienced the pain of lost love, offering hope and empowerment to help them take control of their lives again. This book is for anyone looking to heal, grow, and move forward with their best life in mind.', 'Rithvik Singh', '2023-06-15', 'Self-Help', '9780143456789', 10.50, 240, 'English', 'Penguin India'),
('Game of Thrones', 'Game of Thrones, the first book in George R. R. Martin’s A Song of Ice and Fire series, is a monumental work of fantasy that weaves together political intrigue, war, and betrayal in a world on the brink of turmoil. Set in the fictional continents of Westeros and Essos, the novel introduces a sprawling cast of characters, each with their own motivations, secrets, and struggles. At its core, Game of Thrones is a story about power—who has it, who seeks it, and how far people will go to obtain it. The book is renowned for its complex characters, unpredictable plot twists, and morally gray areas. Martin does not shy away from depicting the brutal realities of war and the consequences of power struggles. The narrative shifts between various perspectives, from the noble Stark family in the North to the ruthless Lannisters in the South, and from the exiled Daenerys Targaryen to the enigmatic Tyrion Lannister. Throughout the novel, themes of loyalty, betrayal, honor, and survival are explored in rich detail. Game of Thrones has captivated millions of readers around the world, with its intricate world-building and its examination of the human condition. The novel’s brutal honesty and complex characters have redefined the fantasy genre, blending elements of medieval history with rich mythical storytelling. Fans of epic fantasy will find themselves drawn into a world where alliances shift, families feud, and nothing is ever truly as it seems. Game of Thrones is a compelling read for anyone who enjoys dark, intricate tales of politics, power, and the fight for survival.', 'George R. R. Martin', '1996-08-06', 'Fantasy', '9780553103540', 19.99, 694, 'English', 'Bantam Books'),
('All for Love', 'All for Love, written by John Dryden, is a tragic romance that explores the themes of love, sacrifice, and the complexities of human emotion. Set in the historical context of ancient Rome, the play tells the story of Antony and Cleopatra, whose passionate relationship leads to betrayal, heartache, and ultimately, tragedy. Dryden presents the timeless struggle between duty and desire, as the lovers face overwhelming odds in their quest for each other. The play emphasizes the self-destructive nature of obsessive love and the consequences of putting personal desires above all else. Dryden’s masterful use of language and dramatic tension brings the emotional depth of the characters to life, making this work an enduring example of the tragic genre. The themes of sacrifice, loyalty, and love’s inability to conquer all obstacles resonate across time, as readers are left contemplating the nature of love and its consequences. All for Love remains a seminal work in the English dramatic tradition, offering powerful insight into the emotional dynamics of love, loss, and the consequences of decisions driven by passion.', 'John Dryden', '1678-01-01', 'Drama', '9780140431001', 8.99, 120, 'English', 'Penguin Classics'),
('The Boy Without a Name', 'The Boy Without a Name is a moving story written by Danish Dhamani about courage, dreams, and self-discovery. The novel centers on a young boy who struggles to understand his identity and place in the world. As he embarks on a journey of self-exploration, he encounters various characters and challenges that help him discover the power of his own resilience and strength. The book highlights themes such as the importance of perseverance, the value of inner strength, and the significance of pursuing one’s dreams regardless of external circumstances. The boy’s journey serves as a metaphor for anyone who has faced self-doubt or confusion while navigating life’s challenges. Through his personal growth, readers are reminded that identity is not determined by external labels or others’ expectations, but by the choices and actions we take in our own lives. The Boy Without a Name is a story of hope and transformation, encouraging readers to embrace their own unique journey toward self-empowerment.', 'Danish Dhamani', '2021-11-10', 'Fiction', '9789391549822', 10.99, 250, 'English', 'Om Books International'),
('The Lion Who Saw Himself in the Water', 'The Lion Who Saw Himself in the Water is a beautifully illustrated fable written by Hassan S. M. that explores the theme of self-awareness and inner strength. The story follows a lion who, while drinking from a waterhole, sees his reflection and becomes intrigued by the image staring back at him. As the lion contemplates his appearance, he embarks on a journey of self-discovery, eventually realizing his own strength and the importance of self-confidence. The story is simple yet profound, offering young readers a valuable lesson about the power of self-reflection and understanding one’s own worth. The Lion Who Saw Himself in the Water is a gentle reminder that we all have the ability to overcome challenges when we understand and believe in our own potential. Through its accessible narrative and beautiful illustrations, the fable encourages children to embrace their inner strength and trust in themselves.', 'Hassan S. M', '2019-06-15', 'Children''s Literature', '9788129903936', 5.99, 64, 'English', 'Rupa Publications'),
('The Man and the Fox', 'The Man and the Fox is an allegorical tale written by Amitabh Bhattacharya that delves into the complex relationship between a man and a fox. The story explores themes such as trust, loyalty, and the blurred lines between humanity and nature. The man and the fox form an unlikely bond, one that forces both of them to question their own instincts and beliefs. The fox, known for its cunning and elusive nature, represents the wild and untamed side of life, while the man symbolizes reason and civilization. The tale examines how these two forces, seemingly opposed, can coexist and learn from one another. The story challenges readers to reflect on their own relationships with the natural world and to question the assumptions they have about what it means to be human. With its thought-provoking narrative and philosophical undertones, The Man and the Fox is an allegory that invites readers to consider deeper truths about nature, society, and the human condition.', 'Amitabh Bhattacharya', '2018-03-22', 'Allegory', '9789388043039', 9.99, 150, 'English', 'HarperCollins India');

-- INSERT INTO Book (title, description, author_name, publication_date, genre, isbn, price, pages, language, publisher) 
-- VALUES 
-- ('To Kill a Mockingbird', 'A powerful novel exploring racial injustice and moral growth in the 1930s South through the eyes of Scout Finch.', 'Harper Lee', '1960-07-11', 'Historical Fiction', '9780061120084', 14.99, 281, 'English', 'J.B. Lippincott & Co.'),
-- ('The Psychology of Money', 'Morgan Housel examines how emotions and behavior shape financial success, emphasizing long-term mindset over knowledge.', 'Morgan Housel', '2020-09-08', 'Finance', '9780857197689', 12.99, 256, 'English', 'Harriman House'),
-- ('Charlotte''s Web', 'A timeless tale of friendship and loyalty between a pig named Wilbur and a spider named Charlotte, highlighting themes of sacrifice.', 'E. B. White', '1952-10-15', 'Children''s Literature', '9780064400558', 7.99, 192, 'English', 'Harper & Brothers'),
-- ('I Don''t Love You Anymore', 'Rithvik Singh offers practical advice for healing and rediscovering self-worth after a painful breakup.', 'Rithvik Singh', '2023-06-15', 'Self-Help', '9780143456789', 10.50, 240, 'English', 'Penguin India'),
-- ('Game of Thrones', 'The first book in George R. R. Martin''s epic series, weaving political intrigue, war, and betrayal in the world of Westeros.', 'George R. R. Martin', '1996-08-06', 'Fantasy', '9780553103540', 19.99, 694, 'English', 'Bantam Books'),
-- ('All for Love', 'John Dryden''s tragic romance about Antony and Cleopatra explores love, sacrifice, and the conflict between duty and desire.', 'John Dryden', '1678-01-01', 'Drama', '9780140431001', 8.99, 120, 'English', 'Penguin Classics'),
-- ('The Boy Without a Name', 'A journey of self-discovery as a young boy finds his identity and strength amidst challenges and self-doubt.', 'Danish Dhamani', '2021-11-10', 'Fiction', '9789391549822', 10.99, 250, 'English', 'Om Books International'),
-- ('The Lion Who Saw Himself in the Water', 'A fable about a lion''s journey to self-awareness and the importance of believing in one''s potential.', 'Hassan S. M', '2019-06-15', 'Children''s Literature', '9788129903936', 5.99, 64, 'English', 'Rupa Publications'),
-- ('The Man and the Fox', 'An allegorical tale exploring trust, loyalty, and the relationship between humanity and nature.', 'Amitabh Bhattacharya', '2018-03-22', 'Allegory', '9789388043039', 9.99, 150, 'English', 'HarperCollins India');


INSERT INTO reviews (bookId, title, author, rating, review_text) 
VALUES
(1, 'A Heartfelt Review of To Kill a Mockingbird', 'Alice Johnson', 5, 'This book is an absolute masterpiece. The themes of racial injustice and the innocence of childhood are beautifully intertwined. A must-read for everyone.'),
(2, 'Invaluable Lessons from The Psychology of Money', 'Bob Miller', 4, 'A fantastic book that gives you a new perspective on money and wealth. The stories and lessons are timeless, though a bit repetitive at times.'),
(3, 'A Timeless Classic', 'Emma Clark', 5, 'Charlotte\'s Web is a touching and heartwarming story that teaches the value of friendship and loyalty. The story is as relevant today as when it was first written.'),
(4, 'A Journey of Self-Discovery', 'Sophie Williams', 3, 'I Don\'t Love You Anymore is an honest take on relationships and moving on, but I felt the pacing was slow at times. Still, it has some valuable life lessons.'),
(5, 'An Epic Adventure', 'David Brown', 5, 'Game of Thrones is a brilliant series of books that combines intrigue, fantasy, and deep character development. The world-building is phenomenal.'),
(6, 'A Tale of Love and Sacrifice', 'Grace Davis', 4, 'All for Love is a poignant story about sacrifice and devotion. The prose is beautiful, but the story can be a bit melodramatic at times.'),
(7, 'A Wonderful Story of Courage', 'Liam Evans', 4, 'The Boy Without a Name is a moving and uplifting story that encourages readers to believe in themselves and follow their dreams.'),
(8, 'A Beautiful Lesson in Self-Awareness', 'Olivia Harris', 5, 'The Lion Who Saw Himself in the Water is a beautifully written fable that teaches children about self-awareness and inner strength in a simple yet profound way.'),
(9, 'An Allegorical Masterpiece', 'John Scott', 5, 'The Man and the Fox is an excellent allegory that explores the complexities of human nature and relationships in a way that is both thought-provoking and entertaining.');
